// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAw2vp5arOcVtlQfLLaw4svSJnR-SBRhl0',
    appId: '1:448603547585:web:52dee22d328962afc4b140',
    messagingSenderId: '448603547585',
    projectId: 'scribbles-25225',
    authDomain: 'scribbles-25225.firebaseapp.com',
    storageBucket: 'scribbles-25225.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDXx0_PMkNfXrpkGM_RREHy31PrGGSeoFo',
    appId: '1:448603547585:android:9ebcff9766c2ac94c4b140',
    messagingSenderId: '448603547585',
    projectId: 'scribbles-25225',
    storageBucket: 'scribbles-25225.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCz46JuZ-44lFhKuQbD7XEQWLQm0w4L4eU',
    appId: '1:448603547585:ios:33d162f742a8d544c4b140',
    messagingSenderId: '448603547585',
    projectId: 'scribbles-25225',
    storageBucket: 'scribbles-25225.firebasestorage.app',
    iosClientId: '448603547585-hjgp8fa8e09fos313e1hfuu5jjbsopkf.apps.googleusercontent.com',
    iosBundleId: 'com.example.scribbles',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCz46JuZ-44lFhKuQbD7XEQWLQm0w4L4eU',
    appId: '1:448603547585:ios:33d162f742a8d544c4b140',
    messagingSenderId: '448603547585',
    projectId: 'scribbles-25225',
    storageBucket: 'scribbles-25225.firebasestorage.app',
    iosClientId: '448603547585-hjgp8fa8e09fos313e1hfuu5jjbsopkf.apps.googleusercontent.com',
    iosBundleId: 'com.example.scribbles',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAw2vp5arOcVtlQfLLaw4svSJnR-SBRhl0',
    appId: '1:448603547585:web:6c6143aa147ad25bc4b140',
    messagingSenderId: '448603547585',
    projectId: 'scribbles-25225',
    authDomain: 'scribbles-25225.firebaseapp.com',
    storageBucket: 'scribbles-25225.firebasestorage.app',
  );
}
